### PR TITLE
Mark / Change Item Names

### PR DESCRIPTION
**Pull request by markccchiang**
1. The changed item names are 
    "Right Ascension Range" --> "RA Range"
    "Declination Range" --> "Dec Range"
    "CasaImageLoader" --> "ImageViewer"

2. The name of desktop/server application is also changed: 
    "CartaVis" --> "CARTA"

3. The tool bar for Mac is rearranged:
    moving "Copyright and License" and "Version 0.9" into the CARTA application tool bar.

4. Add a script "carta/scripts/setupDesktopForMac.sh" in order to setup the new CARTA name app for Mac.

### CODE REVIEW

**Comment by ajm-asiaa** [comment]
I tested this on Mac and CentOS7. I can confirm all new modifications work.

We just need to be aware that the "casa-pkg" packaging template needs to be changed in order to pick up the name change of 'desktop' to 'CARTA'.
For Mac:
```
/casa-pkg/packaging/template/osx/Carta.app/Contents/MacOS
CARTA@ -> @@WS@@/Contents/MacOS/CARTA
```
Made with a symbolic link: **ln -s @@WS@@/Contents/MacOS/CARTA** 

For Linux:
```
/casa-pkg/packaging/template/linux/carta-distro/bin
CARTA -> @@WS@@/CARTA
```
Similarly, made with a symbolic link **ln -s @@WS@@/CARTA CARTA**

Of course the make-app-carta command needs to be similarly changed to pick up CARTA.app instead of desktop.app (only for Mac):
```./make-app-carta -ni -v out=/tmp  ws=$CARTABUILDHOME/build/cpp/desktop/CARTA.app```

In addition, we need to remember to change 'appname=desktop' to 'appname=CARTA' in 39 of carta.sh. For now I can make the change in the script for final packaging, as I know in future we hope to either modify carta.sh more or do away with it. 
Or maybe we should change it now, just to be sure there is no way for it to cause confusion with anyone. Current location is seems to be
```carta/scripts/legacy/carta.sh```

Anyway, I believe this commit can be safely merged as long as the packaging person is aware of the changes new.

**Review by ajm-ska — APPROVED** [review]
I tested this on Mac and CentOS7. I can confirm all new modifications work.

We just need to be aware that the "casa-pkg" packaging template needs to be changed in order to pick up the name change of 'desktop' to 'CARTA'.
For Mac:

/casa-pkg/packaging/template/osx/Carta.app/Contents/MacOS
CARTA@ -> @@WS@@/Contents/MacOS/CARTA

Made with a symbolic link: ln -s @@WS@@/Contents/MacOS/CARTA

For Linux:

/casa-pkg/packaging/template/linux/carta-distro/bin
CARTA -> @@WS@@/CARTA

Similarly, made with a symbolic link ln -s @@WS@@/CARTA CARTA

Of course the make-app-carta command needs to be similarly changed to pick up CARTA.app instead of desktop.app (only for Mac):
./make-app-carta -ni -v out=/tmp ws=$CARTABUILDHOME/build/cpp/desktop/CARTA.app

In addition, we need to remember to change 'appname=desktop' to 'appname=CARTA' in line 39 of carta.sh. For now I can make the change in the script for final packaging, as I know in future we hope to either modify carta.sh more or do away with it.
Or maybe we should change it now, just to be sure there is no way for it to cause confusion with anyone. Current location is seems to be
carta/scripts/legacy/carta.sh

Anyway, I believe this commit can be safely merged as long as the packaging person is aware of the new changes.

**Comment by grimmerk** [comment]
@ajm-asiaa  :+1:

Thank you for the checking. I suggest to do it now (not today, but just recently). Can you summary a short checklist and we can modify them and assign who will do which item?

**Comment by grimmerk** [comment]
check list [draft]:
- [ ] check1

**Comment by kswang1029** [comment]
Thank for the efforts. I do see the commits are effective. Just a minor issue, please also change the "Carta" in the toolbar of desktop version to "CARTA" (i.e. all capital)
screen shot 2017-04-24 at 1 11 26 pm

**Review by grimmerk — APPROVED** [review]

**Comment by markccchiang** [comment]
I have updated this branch according to @kswang1029's suggestion. Also, I have updated the `carta/config/config.json` to the current version according to @grimmer0125's suggestion. I am not sure is it a good way to put additional changes in this branch. Let me know if you have complains.

**Comment by ajm-ska** [comment]
Modification I believe we should make to 'carta.sh', related to this pull request only:

**Change carta.sh appname=CARTA**
As this commit has changed desktop to CARTA, we need to modify this on line 39.

**Comment by grimmerk** [comment]
@ajm-asiaa , thank you for the summary. 

I think some of them are not belonging to this pull request. Please only leave the related and needed change to this pull request (`change the app name part`?). You can update your original post.

Regarding the other improvement, either creating new GitHub issues, or use 
[build_deploy_todo_issues](https://docs.google.com/document/d/1vv2UL71ui-toRerYWCcd9uF6bx2ov9bPpQN6ZLlBU9E/edit) or
[Improve the script to launch released carta and ogranized some needed folder](https://docs.google.com/document/d/1oeyx2CgMbp40Vbl0di0t7GMqe1RRj7lUjPdiY7L-Ip8/edit)

**Comment by ajm-ska** [comment]
OK. I updated the post and put the original list in the "Improve the script to launch released carta and ogranized some needed folder" document instead.

**Comment by grimmerk** [comment]
I'm going to merge this, and willchange `'appname=desktop' to 'appname=CARTA' in line 39 of carta.sh.`

**Pull request merged**
