### PR TITLE
Remove hover behaviour for regions

### PR DESCRIPTION
**Pull request by JamieDass**
This change removes the hover behaviour for regions. Previously, hovering over a region would highlight its control points etc but at a performance cost. This behaviour does not really seem necessary.
This change resolves the cursor lag reported in [issue #105](https://github.com/CARTAvis/carta/issues/105)

### CODE REVIEW

**Comment by kswang1029** [comment]
is this remove action the only solution to fix the performance issue? Actually in casaViewer, when multiple regions present, a region will be highlighted when hovered.

**Comment by JamieDass** [comment]
As far as I can see, with the way that Regions are created and managed in Carta right now, removing the behaviour is the only way to solve this performance lag. I don't think we lose much by removing it.

In the future it might make sense to rewrite the underlying Region code and it could be reintroduced if that happens but that's beyond my scope.

**Comment by low-sky** [comment]
I agree that this doesn't make much sense to polish given the impending changes to UI and architecture.

**Comment by kswang1029** [comment]
OK. Verified. Propose to merge to dev. Thanks for fixing this.

**Pull request merged**
