### PR TITLE
PVimage/cursor

### PR DESCRIPTION
**Pull request by CNOCycle**
This pull request is based on #42.

I am trying to solve the third known issue in #42 :
> casacore always assumes the spectral axis is freq(Hz).

Now, CARTA can show radio velocity information in the cursor.

This feature will be enhanced and controlled by the user in the future if UI side is improved.

### CODE REVIEW

**Comment by grimmerk** [comment]
Here is the change(added) list.
[add velocity in cursor](https://github.com/CARTAvis/carta/pull/43/commits/8a3d83baa42c375fc1a4fc2ac0ce528767d277ff)
[Label velocity 'VRAD'](https://github.com/CARTAvis/carta/pull/43/commits/67d719066f6a41b44985ceaeacf818681f3f4d78)
[improvements for cursor](https://github.com/CARTAvis/carta/pull/43/commits/6d0cc5bef3b3f5011b92c00a6f963104309d6fa1)

 But miss some commits in #42 
remove 'm_axisDisplayInfos' in AstGridPlotter class
remove _make2dFrameCelestial in AstGridPlotter.h
modify comment in FitsHeaderExtractor
fix for warning [-Wformat-security] in WCSPlotter
fix for warning [-Wformat-zero-length] in WCSPlotter
Use errorString to return error message.

**Comment by grimmer0125** [comment]
@CNOCycle , which pull request/commit changes frequency to velocity? Label velocity 'VRAD'?

**Comment by grimmerk** [comment]
Here is some note about m_casaCS, 
```
m_image is CCImage.  // is inherted from IImage.h
..
m_image->getDataSlice( frameSlice ); // IImage.h's ImageInterface has the other two interface, this line is RawViewInterface, image data itself
..
m_image-> metaData() return Carta::Lib::Image::MetaDataInterface, use casa ->wcs ->calculate cursor
..
CoordinateFormatterInterface::SharedPtr cf( m_image-> metaData()-> coordinateFormatter()-> clone() );
..
QStringList list = cf-> formatFromPixelCoordinate( pixel );

    CCCoordinateFormatter::formatFromPixelCoordinate( const CoordinateFormatterInterface::VD & pix )   
	..
	m_casaCS is  casa::CoordinateSystem
	..
```

**Comment by grimmerk** [comment]
I notice that there is another place uses `MetaDataInterface`, 
```
Colormap.cpp
std::pair<double,double> Colormap::_convertIntensity( const QString& oldUnit, const QString& newUnit,

                //First, we need to make sure the x-values are in Hertz.
                std::vector<double> hertzValues;
                auto result = Globals::instance()-> pluginManager()
                                                         -> prepare <Carta::Lib::Hooks::ConversionSpectralHook>(image,
                                                                 "", UnitsFrequency::UNIT_HZ, valuesX );
                auto lam = [&hertzValues] ( const Carta::Lib::Hooks::ConversionSpectralHook::ResultType &data ) {
                    hertzValues = data;
                };
                try {
                    result.forEach( lam ); // use  SpectralConversionPlugin
                }

SpectralConversionPlugin::handleHook( BaseHook & hookData ){
	CCCoordSystemConverter in  CCMetaDataInterface.cpp : public Carta::Lib::Image::MetaDataInterface
```
Is it related to intensity unit conversion? @CNOCycle , @kswang1029, @markccchiang

**Review by grimmerk — APPROVED** [review]

**Pull request merged**
