### PR TITLE
Mark/remove grid lines

### PR DESCRIPTION
**Pull request by markccchiang**
This branch is merged with previous pull requested branches: "mark/reLocateConfigJson", "grimmer/fixIncompatibleAxesCrash" and "grimmer/fixAnimatorCrash". There is only one file changed compared to my last pull request, which is 

$CARTAWORKHOME/CARTAvis/carta/cpp/core/Data/Image/Grid/DataGrid.cpp.

It removes the grid lines as the default setting for Carta image viewer. The grid lines can be called back by clipping the "Image Settings" -> "Grid" -> "Grid Lines (checkbox)."

### CODE REVIEW

**Comment by kswang1029** [comment]
can we put default gridline on/off option in config.json?

**Comment by markccchiang** [comment]
I think this default option can be added and set in "config.json". Let me
try to modify codes tomorrow.

2017-03-29 16:51 GMT+08:00 kswang1029 <notifications@github.com>:

**Comment by kswang1029** [comment]
Awesome! I believe there will be more like default grid-on:off freedom for users. Let me try to make a list.

**Comment by grimmerk** [comment]
@markccchiang  Why do you merge the other branches ? `Develop` can do the `merge part`.  Or you want to use the same branch to continue the following work? This is the only reason I can think of.

**Comment by markccchiang** [comment]
I see. Sorry for that! I just test the other branches in my codes. Next
time I will divide them, so you can easily check which part is unique in my
pull request.


Grimmer <notifications@github.com>於 2017年4月1日 週六，下午4:32寫道：

**Comment by kswang1029** [comment]
I can build this branch with docker. However, I cannot load any images. Errors below:
2017-04-05 05:22:11,017 DEBUG    93 Application Debug: Viewer has been initialized.
2017-04-05 05:22:12,213 INFO        SessionSocketConnection Closing web socket response loop.
2017-04-05 05:22:16,538 INFO        WebSocketSessionServlet Creating endpoint at URI: /pureweb/ws/app/unix:0.0/1/93/1
2017-04-05 05:22:17,489 DEBUG       ManagedService Creating new queue for responses for connectionId: 1
2017-04-05 05:22:17,491 INFO        SessionSocketConnection Starting web socket response loop.
2017-04-05 05:22:43,278 DEBUG    93 Application Warning: Could not find a disk cache plugin.
2017-04-05 05:22:43,279 DEBUG    93 Application  (/home/developer/src/CARTAvis/carta/cpp/core/Data/Image/DataSource.cpp:66, Carta::Data::DataSource::DataSource())
2017-04-05 05:22:43,281 DEBUG    93 Application Warning: wcsgrid: Could not find any WCS grid renderers
2017-04-05 05:22:43,282 DEBUG    93 Application  (/home/developer/src/CARTAvis/carta/cpp/core/Data/Image/Grid/DataGrid.cpp:210, void Carta::Data::DataGrid::_initializeGridRenderer())
2017-04-05 05:22:43,282 DEBUG    93 Application Warning: wcsgrid: Creating dummy grid renderer
2017-04-05 05:22:43,282 DEBUG    93 Application  (/home/developer/src/CARTAvis/carta/cpp/core/Data/Image/Grid/DataGrid.cpp:217, void Carta::Data::DataGrid::_initializeGridRenderer())
2017-04-05 05:22:43,283 DEBUG    93 Application Warning: "Could not find any plugin to load image"
2017-04-05 05:22:43,283 DEBUG    93 Application  (/home/developer/src/CARTAvis/carta/cpp/core/Data/Image/DataSource.cpp:837, QString Carta::Data::DataSource::_setFileName(const QString&, bool*))
2017-04-05 05:22:43,283 DEBUG    93 Application Warning: "Could not find any plugin to load image"
2017-04-05 05:22:43,283 DEBUG    93 Application  (/home/developer/src/CARTAvis/carta/cpp/core/Data/Error/ErrorManager.cpp:81, void Carta::Data::ErrorManager::registerWarning(const QString&))

**Comment by markccchiang** [comment]
Thank you for the question! This is because this branch is merged with my
previous branch "mark/reLocateConfigJson" where I changed the default path
of the configuration file "config.json." Now I synchronize this branch with
the current develop version. That should be no problem.

2017-04-05 13:27 GMT+08:00 kswang1029 <notifications@github.com>:

**Pull request merged**
