### PR TITLE
[mark/changeCacheFileLocation] change the default path of SQLite cache under user's CARTA home directory

### PR DESCRIPTION
**Pull request by markccchiang**
This PR is for issue #189. The new location of SQLite cache file is under user's home directory: `$(HOME)/CARTA/cache/pcache.sqlite`

### CODE REVIEW

**Comment by ajm-ska** [comment]
There seems to be an issue compiling on Linux (CentOS6 with gcc 4.8.2):

`/home/acdc/cartabuild/CARTAvis/carta/cpp/plugins/PCacheLevelDB/PCacheLevelDB.cpp:52:5: warning: unused parameter ‘error’ [-Wunused-parameter]
     readEntry( const QByteArray & key, QByteArray & val, QByteArray & error ) override
     ^
`

`/home/acdc/cartabuild/CARTAvis/carta/cpp/plugins/PCacheLevelDB/PCacheLevelDB.cpp:69:5: warning: unused parameter ‘error’ [-Wunused-parameter]
     setEntry( const QByteArray & key, const QByteArray & val, const QByteArray & error ) override
     ^
make[3]: *** [PCacheLevelDB.o] Error 1
`

**Comment by grimmerk** [comment]
@ajm-asiaa ,  LevelDB is not necessary for now. We can disable it for an urgent need. 
In plugins.pro
```
unix:macx {
# Disable PCacheLevelDB plugin on Mac, since build carta error with LevelDB enabled.
}
else{
  SUBDIRS += PCacheLevelDB
}
```

**Comment by markccchiang** [comment]
To avoid the compiling error on CentOS, I just comment this code line in `PCacheLevelDB.cpp`. You can pull the new repository an try it again.

**Comment by ajm-ska** [comment]
Thanks. That fixed the CentOS compile error. I can confirm it works on Linux
(I will just need to modify setupcartavis.sh in order to create a 'cache' directory in ~/CARTA first, otherwise the pcache.sqlite file doesn't get created).

Currently waiting to test on Mac. Travis-CI seems to be busy.

**Comment by appolloford** [comment]
I remember that this line have been removed in the develop branch. I think you can directly merge the commit `91e9fc9`.

**Comment by ajm-ska** [comment]
Confirmed to work on Mac too.

**Pull request merged**
